import * as yup from "yup";

export const peopleValidator = yup.object().shape({
    nombre: yup.string().required(),
    anio_nacimiento: yup.string().required(),
    color_ojos: yup.string(),
    genero: yup.string().required(),
    color_pelo: yup.string(),
    altura: yup.string().required(),
    masa: yup.string().required(),
    color_piel: yup.string().required(),
    pais_origen: yup.string(),
    peliculas: yup.array().default([]),
    especies: yup.array().default([]),
    vehiculos: yup.array().default([]),
    naves_espaciales: yup.array().default([]),
    url: yup.string().default('').url(),
    created: yup.string(),
    edited: yup.string()
    // name: yup.string().required(),
    // birth_year: yup.string().required(),
    // eye_color: yup.string(),
    // gender: yup.string().required(),
    // hair_color: yup.string(),
    // height: yup.string().required(),
    // mass: yup.string().required(),
    // skin_color: yup.string().required(),
    // homeworld: yup.string(),
    // films: yup.array().default([]),
    // species: yup.array().default([]),
    // starships: yup.array().default([]),
    // vehicles: yup.array().default([]),
    // url: yup.string().default('').url(),
    // created: yup.string(),
    // edited: yup.string(),
});